name: math_solver
description: A new Flutter package project.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  test: ^1.15.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
