name: math_solver
description: A math solver package.
version: 0.1.0
author: aaro.luo
homepage: https://github.com/aaroluo/math_solver

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  test: ^1.15.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
