name: math_solver
description: A math solver package.
version: 0.1.0
author: aaro.luo
homepage: https://github.com/aaroluo/math_solver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.2
  meta: ^1.3.0
  rational: ^1.2.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.15.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
