name: math_solver
description: A math solver package.
version: 0.1.0
author: aaro.luo
homepage: https://github.com/aaroluo/math_solver

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
