name: math_solver
description: A math solver package.
version: 0.1.0
author: aaro.luo
homepage: https://github.com/aaroluo/math_solver

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  equatable: ^1.2.5
  json_serializable: ^3.5.1

dev_dependencies:
  build_runner: ^1.10.13
  pedantic: ^1.9.2
  test: ^1.15.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
